stages:
  - deploy

deployToDigitalOcean:
  tags:
    - deploy
  stage: deploy
  script:
    - echo "Deploying..."
    - source .env.prod
    - cd $DEPLOY_PATH
    - git fetch origin
    - git checkout $DEPLOY_BRANCH
    - git pull origin $DEPLOY_BRANCH
    - npm install
    - pm2 stop all
    - pm2 start ./bin/www --watch
    - pm2 save
